### ISSUE TITLE
RAF-Manager is throwing window is not defined.

### ISSUE THREAD

**Issue by zachjonesnoel** [lindelof/particles-bg#18]
After installation of particles-bg - "^2.5.5", the first time when running it worked. And now when I did npm i and tried to run the projects, raf-manager is throwing this error. 
I don't see raf-manager GitHub repo, even npm doesn't have it. If in case something on raf-manager has changed or deprecated, please update particles-bg package as well. 
![image](https://user-images.githubusercontent.com/12515425/132016984-8713e6b3-8a2f-49f2-af54-21647d46c17e.png)

**Comment by zachjonesnoel** [comment]
When I reinstalled the package and tried to build the project. 
`ReferenceError: window is not defined
    at /home/ec2-user/environment/nextjs-landingpage/node_modules/raf-manager/build/RAFManager.min.js:9:254
    at /home/ec2-user/environment/nextjs-landingpage/node_modules/raf-manager/build/RAFManager.min.js:9:461
    at /home/ec2-user/environment/nextjs-landingpage/node_modules/raf-manager/build/RAFManager.min.js:9:84
    at Object.<anonymous> (/home/ec2-user/environment/nextjs-landingpage/node_modules/raf-manager/build/RAFManager.min.js:9:153)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18) {
  type: 'ReferenceError'
}`

**Comment by zachjonesnoel** [comment]
When I reinstalled the package and it worked fine but when I tried to build the project, it threw the same error.

**Comment by joeyscarim** [comment]
Are you using nextjs?

If so, you can dynamically import the package on the client side only:

```
import dynamic from 'next/dynamic';

const ParticlesBg = dynamic(() => import('particles-bg'), {
  ssr: false,
});
```

**Comment by zachjonesnoel** [comment]
Yea, I'm using NextJS. Let me try it out. Thanks @joeyscarim
